x-common-vars: &common-vars
  ENVIRONMENT: production
  TZ: Europe/Brussels

services:
  nginx:
    container_name: nginx
    image: ghcr.io/bobbydusk/dance2move/nginx:main
    environment: *common-vars
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
    networks:
      - nginx
    volumes:
      - ./static:/static:rw
    depends_on:
      - api

  api:
    image: ghcr.io/bobbydusk/dance2move/api:main
    container_name: api
    environment: *common-vars
    restart: unless-stopped
    ports:
      - 8000:8000
    networks:
      - nginx
    volumes:
      - ./static:/static:rw

networks:
  nginx:
