[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "hypercorn>=0.17.3",
    "librosa>=0.11.0",
    "matplotlib>=3.10.3",
    "quart>=0.20.0",
]

[project.scripts]
start = "backend:main"
